# Generated by Django 6.0 on 2025-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('subject', models.CharField(max_length=50)),
                ('subject_image', models.ImageField(upload_to='./Images/')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('eligible', models.BooleanField()),
            ],
        ),
    ]
